Back-End/movie_lovers/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from datetime import datetime
import uuid
from werkzeug.security import generate_password_hash, check_password_hash
import secrets
from flask_login import LoginManager, UserMixin
from flask_marshmallow import Marshmallow

# flask db init
# flask db migrate -m "Initial migration."
# flask db upgrade
db = SQLAlchemy()
login_manager = LoginManager()
ma = Marshmallow()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)



class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key = True, unique = True)
    email = db.Column(db.String(150), nullable = False, unique = True)
    password = db.Column(db.String, nullable = False)
    token = db.Column(db.String, nullable = False, unique = True)
    date_created = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)
    movie = db.relationship('Movie', backref = 'owner', lazy = True)

    def __init__(self, email, password, token = '', id = ''):
        self.id = self.set_id()
        self.email = email
        self.password = self.set_password(password)
        self.token = self.set_token(24)

    def set_id(self):
        return str(uuid.uuid4())


    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)
        return self.pw_hash

    
    def set_token(self, lenght):
        return secrets.token_hex(lenght)


class Movie(db.Model):
    id = db.Column(db.String, primary_key=True, unique = True)
    name = db.Column(db.String(150), nullable=False, unique = True)
    genre = db.Column(db.String(100), nullable=True)
    year = db.Column(db.String(200), nullable=True)
    rating = db.Column(db.Integer, default=0)
    user_token = db.Column(db.String, db.ForeignKey('user.token'), nullable = False)


    def __init__(self, name, genre, year, rating, user_token, id = ''):
        self.id = self.set_id()
        self.name = name
        self.genre = genre
        self.year = year
        self.rating = rating
        self.user_token = user_token

    def set_id(self):
        return (secrets.token_urlsafe())


class MovieSchema(ma.Schema):
    class Meta:
        fields = ['id', 'name','genre', 'year', 'rating']

movie_schema = MovieSchema()
movies_schema = MovieSchema(many=True)

Back-End/movie_lovers/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField 
from wtforms.validators import DataRequired, Email

class UserLoginForm(FlaskForm):
    # email, password, submit attributes
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit_button = SubmitField()

Back-End/movie_lovers/__init__.py
from flask import Flask
from config import Config
from .authentication.routes import auth
from .api.routes import api
from .site.routes import site
from flask_migrate import Migrate
from .models import db, login_manager, ma
from flask_cors import CORS 
from .helpers import JSONEncoder
# CORS (Cross Origin Resource Sharing) allows access to resources from other domains.
# A good use case for this is a web app trying to fetch data from an API on another domain. 
# CORS is only required when trying to fetch data from a browser, 
# as browsers by default will block requests to different origins (domains)

# instantiating a new flask app
app = Flask(__name__)
app.config.from_object(Config)

app.register_blueprint(auth)
app.register_blueprint(site)
app.register_blueprint(api)

db.init_app(app)

login_manager.init_app(app)
login_manager.login_view = 'auth.signin'

ma.init_app(app)

migrate = Migrate(app, db)

CORS(app)
app.json_encoder = JSONEncoder

Back-End/movie_lovers/api/routes.py
from flask import Blueprint, request, jsonify, url_for
from movie_lovers.helpers import token_required
from movie_lovers.models import User, Movie, db, movie_schema, movies_schema
from movie_lovers.ml.ml import movie_suggestion


api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/getdata')
def getdata():
    return {'item_1': 'hello', 'item_2': 'worlds'}


# CRUD functionality below

@api.route('/movies', methods=['POST'])
@token_required
def create_movie(current_user_token):
    name = request.json['name']
    genre = request.json['genre']
    year= request.json['year']
    rating = request.json['rating']
    token = current_user_token.token

    movie = Movie(name,genre,year,rating, user_token = token)

    db.session.add(movie)
    db.session.commit()

    response = movie_schema.dump(movie)
    return jsonify(response)



@api.route('/movies', methods = ['GET'])
@token_required
def get_movies(current_user_token):
    owner = current_user_token.token
    movies = Movie.query.filter_by(user_token = owner).all()
    response = movies_schema.dump(movies)
    return jsonify(response)


@api.route('/movies/<id>', methods= ['GET'])
@token_required
def get_movie(current_user_token, id):
    movie = Movie.query.get(id)
    if movie:
        response = movie_schema.dump(movie)
        return jsonify(response)
    else:
        return jsonify({'Error': 'That movie does not exist!'})



@api.route('/movies/<id>', methods= ['POST', 'PUT'])
@token_required
def update_movie(current_user_token, id):
    movie = Movie.query.get(id)
    # print(movie)
    if movie:
        movie.name = request.json['name']
        movie.genre = request.json['genre']
        movie.year = request.json['year']
        movie.rating = request.json['rating']
        movie.token_token = current_user_token.token
        db.session.commit()

        response = movie_schema.dump(movie)
        return jsonify(response)
    else:
        return jsonify({'Error': 'That movie does not exist!'})

# DELETE ROUTE
@api.route('/movies/<id>', methods= ['DELETE'])
@token_required
def delete_movies(current_user_token, id):
    movie = Movie.query.get(id)
    if movie:
        db.session.delete(movie)
        db.session.commit()
        return jsonify({'Success': f'Movie ID #{movie.id} has been deleted'})
    else:
        return jsonify({'Error': 'That movie does not exist!'})


# Machine Laerning Functionality starts here
@api.route('/suggestedmovies', methods= ['GET'])
@token_required
def suggested_movies(current_user_token):
    suggestedMovies = movie_suggestion(current_user_token)
    if suggestedMovies:
        return jsonify({'suggestedMovies': suggestedMovies})
    else:
        return jsonify({'Error': 'No recommendation is found!'})

Back-End/movie_lovers/authentication/routes.py
from flask import Blueprint, render_template, request, url_for, flash, redirect
from movie_lovers.forms import UserLoginForm
from movie_lovers.models import User, db, check_password_hash
from flask_login import login_user, login_required, logout_user


auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        #print(email, password)

        new_user = User(email, password)
        db.session.add(new_user)
        db.session.commit()
        flash(f'You have successfully registered an account under {email}', 'user-created')
        return redirect(url_for('site.home'))
    
    return render_template('signup.html', form = form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        # print(email, password)

        logged_user = User.query.filter(User.email == email).first()
        if logged_user and check_password_hash(logged_user.password, password):
            login_user(logged_user)
            flash('You are successfully logged in', 'auth-success')
            return redirect(url_for('site.home'))

        else:
            flash('Your Email/Password is incorrect', 'auth-failed')
            #print('failed-auth')
            return redirect(url_for('auth.signin'))



    return render_template('signin.html', form = form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have Successfully logged out', 'auth-success')
    return redirect(url_for('site.home'))

Back-End/movie_lovers/site/routes.py
from flask import Blueprint, render_template
from flask_login import login_required

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

Back-End/movie_lovers/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Movie API</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('site.home') }}">Movie API</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('site.home') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('site.profile') }}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Log out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signin') }}">Sign In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">Sign Up</a>
                </li>
            {% endif %}
            </ul>
        </div>
        </nav>
    <!-- Block content area... marks the begining and the end of base-->
    {% block content %}
    {% endblock content %}


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>